language: r
dist: bionic
cache: packages

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux

r_github_packages:
  - jimhester/lintr
  - MangoTheCat/goodpractice

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  - travis_wait 60 Rscript -e 'goodpractice::gp()'

